### ISSUE TITLE
[bug] 5.0.1 Docker image fails on start up, module not found

### ISSUE THREAD

**Issue by decairn** [zwave-js/zwavejs2mqtt#1335]
### Version

**Checklist:**

- [X] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [X] I have checked the troubleshooting section and my problem is **not** described there.
- [X] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [X] Docker
- [ ] PKG
- [ ] Snap package
- [ ] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 5.0.1
zwave-js version: 7.7.3

### Describe the bug
Fails to start up with a module not found error.

Docker log:
2021-06-11 16:39:42	stdout	}
2021-06-11 16:39:42	stdout	  requireStack: []
2021-06-11 16:39:42	stdout	  code: [32m'MODULE_NOT_FOUND'[39m,
2021-06-11 16:39:42	stdout	[90m    at node:internal/main/run_main_module:17:47[39m {
2021-06-11 16:39:42	stdout	[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)[39m
2021-06-11 16:39:42	stdout	[90m    at Function.Module._load (node:internal/modules/cjs/loader:769:27)[39m
2021-06-11 16:39:42	stdout	[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)[39m
2021-06-11 16:39:42	stdout	Error: Cannot find module '/usr/src/app/bin/www'
2021-06-11 16:39:42	stdout	
2021-06-11 16:39:42	stdout	  ^
2021-06-11 16:39:42	stdout	  throw err;
2021-06-11 16:39:42	stdout	node:internal/modules/cjs/loader:927

Zwave log:
None - doesn't get that far

### To Reproduce

1. Stop existing image (4.5.2), update to latest (docker pull zwavejs/zwavejs2mqtt:latest), restart.
2. Start fails - see error log above.

### Expected behavior

Docker can start up OK and proceed to ZWave application.

### Additional context
Running on a Synology 918+.  The 4.5.2 image works without error, rollback to that is successful, so this is a 5.0.1 change error.

**Comment by barstown** [comment]
Same for me. I rolled back to the 5.0.0 tag with success.

**Comment by ScratMan** [comment]
Same issue with 5.0.1 while 5.0.0 seems to work correctly.

**Comment by Drynael** [comment]
Same here, downgrade to 5.0.0 works

**Comment by joshlawless** [comment]
Same here with 5.0.1

**Comment by eric-silva89** [comment]
Same here with 5.0.1 using raspberry pi 4 with ubuntu image.

**Comment by ttcole1254** [comment]
For what it's worth, when I upgraded from 4.5.2 to 5.0.0 I had the same issue. If I recreated the container from scratch, aka not an upgrade, it works fine. Not sure why, but considering there's almost no configuring to do with this container, it works for me at least for now.

**Comment by D34DC3N73R** [comment]
yeah super weird issue. rolled back to 5.0.0 started up fine. removed the 5.0.0 tag and started up :latest and it was still fine.

**Comment by Sweetgenius19** [comment]
> For what it's worth, when I upgraded from 4.5.2 to 5.0.0 I had the same issue. If I recreated the container from scratch, aka not an upgrade, it works fine. Not sure why, but considering there's almost no configuring to do with this container, it works for me at least for now.

Exact same for me. Working fine after recreating the container.

**Comment by ttcole1254** [comment]
I recreated my container when upgrading from 4.5.2 to 5.0.0, and I updated that to 5.0.2 just now with no issues whatsoever. From what I can tell, the command has changed from "node bin/www" to "node server/bin/www" starting on 5.0.0. I guess simply updating from 4.5.2 to 5.0.0 without recreating it carries over that old command.

**Comment by SKOJau** [comment]
> 
> 
> I recreated my container when upgrading from 4.5.2 to 5.0.0, and I updated that to 5.0.2 just now with no issues whatsoever. From what I can tell, the command has changed from "node bin/www" to "node server/bin/www" starting on 5.0.0. I guess simply updating from 4.5.2 to 5.0.0 without recreating it carries over that old command.

Worked for me, thanks :)

**Comment by robertsLando** [comment]
Like @ttcole1254 said the startup command has changed, seems that docker for some reason doesn't pick up the new command when pulling a new image 🤷🏼‍♂️ I didn't know about that, I'm sorry, there is actually no fix for that you just should delete your local image and then pull and it should work as expected.

**Comment by decairn** [comment]
Delete and new pull worked just fine, thank you
